/** Centralized DOM element references */

export const form = document.querySelector('.add-form')
export const input = document.getElementById('todo-input')
export const listEl = document.querySelector('.todo-list')

export const authSignedIn = document.getElementById('auth-signed-in')
export const authInitial = document.getElementById('auth-initial')
export const authEmail = document.getElementById('auth-email')
export const authSignOut = document.getElementById('auth-sign-out')
export const authCta = document.getElementById('auth-cta')
export const authCtaMessage = document.getElementById('auth-cta-message')
export const authOpenLogin = document.getElementById('auth-open-login')
export const authOpenSignup = document.getElementById('auth-open-signup')
export const authModal = document.getElementById('auth-modal')
export const authModalClose = document.getElementById('auth-modal')?.querySelector('.auth-modal__close')
export const authSigninForm = document.getElementById('auth-signin-form')
export const authSignupForm = document.getElementById('auth-signup-form')
export const authSigninEmail = document.getElementById('auth-signin-email')
export const authSigninPassword = document.getElementById('auth-signin-password')
export const authSignupEmail = document.getElementById('auth-signup-email')
export const authSignupPassword = document.getElementById('auth-signup-password')
export const authMessage = document.getElementById('auth-message')
export const authModalTitle = document.getElementById('auth-modal-title')
export const authModalHint = document.getElementById('auth-modal-hint')
export const authSwitchToSignup = document.getElementById('auth-switch-to-signup')
export const authSwitchToSignin = document.getElementById('auth-switch-to-signin')
export const authTooltip = document.getElementById('auth-tooltip')
export const dragHandleTooltip = document.getElementById('drag-handle-tooltip')
export const crossModeToggleBtn = document.getElementById('cross-mode-toggle')
export const cursorPencilEl = document.getElementById('cursor-pencil')
export const brandHeaderEl = document.getElementById('brand-header')
export const addBlockEl = document.getElementById('add-block')
export const floatingMenuEl = document.getElementById('floating-menu')
export const floatingMenuPencilSlotEl = document.getElementById('floating-menu__pencil-slot')
export const floatingAddBtnEl = document.getElementById('floating-add-btn')

export const todoErrorEl = document.getElementById('todo-error')
export const todoEmptyEl = document.getElementById('todo-empty')
export const emptyStatePartyBtn = document.querySelector('.empty-state__party')
export const appEl = document.getElementById('app')
export const filterRowEl = document.getElementById('filter-row')
export const filterRowSlotEl = document.querySelector('.filter-row-slot')
export const todoAddBtn = document.getElementById('todo-add-btn')
export const todoAddBtnIcon = document.getElementById('todo-add-btn')?.querySelector('.add-form__submit-icon')
export const todoAddBtnSpinner = document.getElementById('todo-add-btn')?.querySelector('.add-form__spinner')
export const todoAddBtnCheck = document.getElementById('todo-add-btn')?.querySelector('.add-form__check')
export const todoChipsAdd = document.querySelectorAll('.add-form__chips .chip')
export const todoFilterButtons = document.querySelectorAll('.filter-btn')
export const todoNoMatchEl = document.getElementById('todo-no-match')
export const statusDropdown = document.getElementById('status-dropdown')
export const statusFilterTrigger = document.getElementById('status-filter-trigger')
export const statusFilterLabel = document.getElementById('status-filter-label')
export const statusDropdownPanel = document.getElementById('status-dropdown-panel')
export const statusDropdownOptions = document.querySelectorAll('.status-dropdown__option')

export const toastEl = document.getElementById('toast')
export const toastMessage = document.getElementById('toast')?.querySelector('.toast__message')
export const toastUndo = document.getElementById('toast')?.querySelector('.toast__undo')

export const themeDarkBtn = document.getElementById('theme-dark')
export const themeLightBtn = document.getElementById('theme-light')
